FROM node:20-alpine
WORKDIR /app
ARG VITE_API_URL=http://localhost:3006/api
ENV VITE_API_URL=$VITE_API_URL
EXPOSE 5173

COPY package*.json ./
RUN npm ci

COPY . .

CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0", "--port", "5173"]
